from __future__ import annotations
from pydantic import BaseModel
from typing import List, Any


# generated by datamodel-codegen


class Image(BaseModel):
    url: str
    nsfwLevel: int = 1
    hasMeta: bool = False
    meta: dict[str, Any] = {}

    def __hash__(self):
        return hash(
            (
                self.url,
                self.nsfwLevel,
                self.hasMeta,
            )
        )


class CivitaiModel(BaseModel):
    id: int
    modelId: int
    trainedWords: List[str] = []
    baseModel: str = ""
    description: str = ""
    images: List[Image] = []

    def __hash__(self):
        return hash((self.id, self.modelId, self.name, tuple(self.trainedWords), self.baseModel, self.description))
