from __future__ import annotations
from pydantic import BaseModel 
from typing import List, Optional, Any


# generated by datamodel-codegen

class Image(BaseModel):
    url: str
    nsfwLevel: int
    width: int
    height: int
    hash: str
    type: str
    meta: Optional[dict[str, Any]]
    availability: str
    hasMeta: bool
    onSite: bool


class CivitaiModel(BaseModel):
    id: int
    modelId: int
    name: str
    trainedWords: List[str]
    baseModel: str
    description: Optional[str]
    images: List[Image]
